[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "reports"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "influxdb-client>=1.50.0",
    "matplotlib>=3.10.8",
    "pandas>=3.0.2",
    "pydantic>=2.11.3",
    "pydantic-settings>=2.9.1",
    "pytest>=9.0.2",
    "pytz>=2026.1.post1",
    "types-pytz>=2026.1.1.20260408",
]

[project.scripts]
net_pnl = "src.scripts.net_pnl:main"
market = "src.scripts.market:main"
trading_volume = "src.scripts.trading_volume:main"
test_signal = "tests.cli:test_signal_client"

[tool.setuptools.packages.find]
include = ["src*", "tests*"]

[tool.pyrefly]
search-path = ["."]
