[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "reports"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=3.0.2",
    "pytest>=9.0.2",
]

[project.scripts]
net_pnl = "src.scripts.daily.net_pnl:main"
market = "src.scripts.daily.market:main"
test_signal = "tests.cli:test_signal_client"
redis_export = "src.scripts.redis_export:main"
redis_report = "src.scripts.redis_timeseries_report:main"

[tool.setuptools.packages.find]
include = ["src*", "tests*"]
