# Gateway host to latest feed config returned by Step 6.
# Keep this in sync after each successful new-listing run.
"localhost:45703": |
  exchange: EXCHANGE_KUCOIN
  is_mainnet: true
  host: "0.0.0.0:41739"
  symbols_per_connection: 20
  symbols: [
    {
        base_currency: "SOL",
        quote_currency: "USDT",
        instrument_type: INSTRUMENT_TYPE_SPOT

      },
      {
          base_currency: "AI"
          quote_currency: "USDT"
          instrument_type: INSTRUMENT_TYPE_SPOT
      },
      {
          base_currency: "ASSET"
          quote_currency: "USDT"
          instrument_type: INSTRUMENT_TYPE_SPOT
      },
      {
          base_currency: "MEGA"
          quote_currency: "USDT"
          instrument_type: INSTRUMENT_TYPE_SPOT
      },
      {
          base_currency: "TESTINGQ"
          quote_currency: "USDT"
          instrument_type: INSTRUMENT_TYPE_SPOT
      },
      {
          base_currency: "BILL"
          quote_currency: "USDT"
          instrument_type: INSTRUMENT_TYPE_SPOT
      },
      {
          base_currency: "TAC"
          quote_currency: "USDT"
          instrument_type: INSTRUMENT_TYPE_SPOT
      }
  ]
